### ISSUE TITLE
change on-off button

### ISSUE THREAD

**Issue by jutky** [tsirkin/jira-rtl#1]
![image](https://user-images.githubusercontent.com/701445/35324680-1812d61a-00fa-11e8-8dd9-ffd3902a514d.png)
The on-off button should be opposite.
When "on" is shown - it should mean that the application is now on and not that if you click the toggle it would be on.
Please, see the following answer that includes this idea: https://ux.stackexchange.com/a/63914/59646

**Comment by tsirkin** [comment]
fixed

**Comment by jutky** [comment]
Thanks a lot.
Now it look better.
