### ISSUE TITLE
The plugin does not support mixed formating

### ISSUE THREAD

**Issue by hezig** [tsirkin/jira-rtl#5]
If I write a Hebrew sentence that includes English words the text goes to the left no matter what
So I have ended up with one sentence to the right and another to the left
If there is one word in Hebrew in the paragraph, all text should go to the right
![MIXED FORMAT EXAMPLE](https://user-images.githubusercontent.com/8088756/58164158-f38f5280-7c8d-11e9-8965-239d23ee942e.png)

**Comment by tsirkin** [comment]
Well,
The plugin desideds on the text direction by the first sentence character
So, if you have english letter as the first letter in a sentence it will be ltr aligned.
Is this what you experience?
